TypeError in line 200 of /work/frasergen/3D/work/shaojie/script/HiC/hic_prepare/hic_pre.snake.py:
'dict' object is not callable
  File "/work/frasergen/3D/work/shaojie/script/HiC/hic_prepare/hic_pre.snake.py", line 200, in <module>
