KeyError in line 16 of /work/frasergen/3D/work/shaojie/script/HiC/hic_prepare/hic_pre.snake.py:
'DATANAMES'
  File "/work/frasergen/3D/work/shaojie/script/HiC/hic_prepare/hic_pre.snake.py", line 16, in <module>
